version: '3.8'
services:
  dynamo:
    image: amazon/dynamodb-local:latest
    restart: always
    ports:
      - '8000:8000'
    command: ['-jar', 'DynamoDBLocal.jar', '-sharedDb', '-dbPath', '/data/db']
    volumes:
      - ./.data/db:/data/db
  dynamo-admin:
    image: aaronshaf/dynamodb-admin
    restart: always
    ports:
      - '8001:8001'
    environment:
      DYNAMO_ENDPOINT: 'http://dynamo:8000'
      AWS_REGION: 'eu-central-1'
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
